### ISSUE TITLE
AEAD wrapper

### ISSUE THREAD

**Issue by rfjakob** [jacobsa/crypto#6]
Hi there, I am about to use SIV in [gocryptfs](https://nuetzlich.net/gocryptfs/), thanks for the great work!

I'll write an [AEAD](https://golang.org/pkg/crypto/cipher/#AEAD) wrapper for that, just wanted to ask if you are interested in having the wrapper upstream in your repo, otherwise I'll keep it in gocryptfs.

**Comment by jacobsa** [comment]
Might as well keep it there for now, but thanks!
